bat_core/main/default/objects/BatchChunkLog__c/BatchChunkLog__c.object-meta.xml
<CustomObject>
    <description>Represents a batch chunk execution.</description>
    <label>Batch chunk log</label>
    <nameField>
        <displayFormat>Batch chunk log {000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch chunk log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bat_core/main/default/objects/BatchChunkLog__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <defaultValue>now()</defaultValue>
    <description>Chunk execution end time.</description>
    <label>End time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/EndTimeMillis__c.field-meta.xml
<CustomField>
    <fullName>EndTimeMillis__c</fullName>
    <defaultValue>0</defaultValue>
    <label>End time (millis)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/JobId__c.field-meta.xml
<CustomField>
    <fullName>JobId__c</fullName>
    <description>The job&#39;s identifier.</description>
    <label>Job ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/RuntimeMillis__c.field-meta.xml
<CustomField>
    <fullName>RuntimeMillis__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Runtime (milliseconds)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <defaultValue>now()</defaultValue>
    <description>Chunk execution start time.</description>
    <label>Start time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/StartTimeMillis__c.field-meta.xml
<CustomField>
    <fullName>StartTimeMillis__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Start time (millis)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bat_core/main/default/classes/bat_BatchTrackingTest.cls
@IsTest
private class bat_BatchTrackingTest {

    @IsTest
    static void run() {
        Id jobId = bat_IDGenerator.generate(Schema.AsyncApexJob.getSObjectType());

        bat_BatchTracking.init(jobId);
        System.assertNotEquals(null, bat_BatchTracking.evt, 'platform event object must be created');
        System.assertNotEquals(null, bat_BatchTracking.evt.Start__c, 'platform event must have its start date/time initialized');

        bat_BatchTracking.report();

        System.assertNotEquals(null, bat_BatchTracking.evt.End__c, 'platform event must have its end date/time initialized');
        System.assertNotEquals(null, bat_BatchTracking.evt.RuntimeMillis__c, 'platform event must have its duration initialized');

        Test.getEventBus().deliver();

        BatchChunkLog__c log = [SELECT
            Id,
            JobId__c,
            Start__c,
            End__c,
            RuntimeMillis__c,
            StartTimeMillis__c,
            EndTimeMillis__c
            FROM BatchChunkLog__c
        ];

        BatchChunkLog__c logCopy = log.clone(false, true, false, false);
        logCopy.StartTimeMillis__c += 1000;
        logCopy.EndTimeMillis__c += 1000;
        insert logCopy;

        bat_BatchTracking.normalize(jobId);
    }
}