bat_core/main/default/objects/BatchChunk__e/BatchChunk__e.object-meta.xml
<CustomObject>
    <description>Represents a batch chunk that finished running, with its start and end time.</description>
    <label>Batch chunk</label>
    <pluralLabel>Batch chunk</pluralLabel>
</CustomObject>

bat_core/main/default/objects/BatchChunk__e/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <defaultValue>now()</defaultValue>
    <description>Chunk execution end time.</description>
    <label>End time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

bat_core/main/default/objects/BatchChunk__e/fields/JobId__c.field-meta.xml
<CustomField>
    <fullName>JobId__c</fullName>
    <description>The job&#39;s identifier.</description>
    <label>Job ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

bat_core/main/default/objects/BatchChunk__e/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <defaultValue>now()</defaultValue>
    <description>Chunk execution start time.</description>
    <label>Start time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/BatchChunkLog__c.object-meta.xml
<CustomObject>
    <description>Represents a batch chunk execution.</description>
    <label>Batch chunk log</label>
    <nameField>
        <displayFormat>Batch chunk log {000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch chunk log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bat_core/main/default/objects/BatchChunkLog__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <defaultValue>now()</defaultValue>
    <description>Chunk execution end time.</description>
    <label>End time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/EndTimeMillis__c.field-meta.xml
<CustomField>
    <fullName>EndTimeMillis__c</fullName>
    <defaultValue>0</defaultValue>
    <label>End time (millis)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/JobId__c.field-meta.xml
<CustomField>
    <fullName>JobId__c</fullName>
    <description>The job&#39;s identifier.</description>
    <label>Job ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/RuntimeMillis__c.field-meta.xml
<CustomField>
    <fullName>RuntimeMillis__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Runtime (milliseconds)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <defaultValue>now()</defaultValue>
    <description>Chunk execution start time.</description>
    <label>Start time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/StartTimeMillis__c.field-meta.xml
<CustomField>
    <fullName>StartTimeMillis__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Start time (millis)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bat_core/main/default/classes/bat_BatchChunkEventTriggerHandler.cls
public without sharing class bat_BatchChunkEventTriggerHandler {
    /**
     * Working with the premise that it will be one event at a time, even though this is bulkified
     * code.
     */
    public bat_BatchChunkEventTriggerHandler(List<BatchChunk__e> records) {
        List<BatchChunkLog__c> logs = new List<BatchChunkLog__c>();

        for (BatchChunk__e event : records) {
            BatchChunkLog__c log = new BatchChunkLog__c(
                Start__c = event.Start__c,
                StartTimeMillis__c = event.StartTimeMillis__c,
                EndTimeMillis__c = event.EndTimeMillis__c,
                End__c = event.End__c,
                RuntimeMillis__c = event.RuntimeMillis__c,
                JobId__c = event.JobId__c
            );
            logs.add(log);
        }
        insert logs;
    }
}