bat_core/main/default/objects/BatchChunk__e/BatchChunk__e.object-meta.xml
<CustomObject>
    <description>Represents a batch chunk that finished running, with its start and end time.</description>
    <label>Batch chunk</label>
    <pluralLabel>Batch chunk</pluralLabel>
</CustomObject>

bat_core/main/default/objects/BatchChunk__e/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <defaultValue>now()</defaultValue>
    <description>Chunk execution end time.</description>
    <label>End time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

bat_core/main/default/objects/BatchChunk__e/fields/JobId__c.field-meta.xml
<CustomField>
    <fullName>JobId__c</fullName>
    <description>The job&#39;s identifier.</description>
    <label>Job ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

bat_core/main/default/objects/BatchChunk__e/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <defaultValue>now()</defaultValue>
    <description>Chunk execution start time.</description>
    <label>Start time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/BatchChunkLog__c.object-meta.xml
<CustomObject>
    <description>Represents a batch chunk execution.</description>
    <label>Batch chunk log</label>
    <nameField>
        <displayFormat>Batch chunk log {000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch chunk log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

bat_core/main/default/objects/BatchChunkLog__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <defaultValue>now()</defaultValue>
    <description>Chunk execution end time.</description>
    <label>End time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/EndTimeMillis__c.field-meta.xml
<CustomField>
    <fullName>EndTimeMillis__c</fullName>
    <defaultValue>0</defaultValue>
    <label>End time (millis)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/JobId__c.field-meta.xml
<CustomField>
    <fullName>JobId__c</fullName>
    <description>The job&#39;s identifier.</description>
    <label>Job ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/PreviousChunkLog__c.field-meta.xml
<CustomField>
    <fullName>PreviousChunkLog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous batch log</label>
    <referenceTo>BatchChunkLog__c</referenceTo>
    <relationshipLabel>Batch chunk log</relationshipLabel>
    <relationshipName>Batch_chunk_log</relationshipName>
    <type>Lookup</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/RuntimeMillis__c.field-meta.xml
<CustomField>
    <fullName>RuntimeMillis__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Runtime (milliseconds)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <defaultValue>now()</defaultValue>
    <description>Chunk execution start time.</description>
    <label>Start time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

bat_core/main/default/objects/BatchChunkLog__c/fields/StartTimeMillis__c.field-meta.xml
<CustomField>
    <fullName>StartTimeMillis__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Start time (millis)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

bat_core/main/default/classes/bat_BatchTracking.cls
public without sharing class bat_BatchTracking {

    @TestVisible
    private static BatchChunk__e evt;

    public static BatchChunk__e init(Id jobId) {
        if (!System.isBatch() && !Test.isRunningTest()) {
            throw new bat_BatchTrackingException('Not in a batch context.');
        }
        Datetime start = System.now();
        evt = new BatchChunk__e(
            JobId__c = jobId,
            Start__c = start,
            StartTimeMillis__c = start.getTime()
        );
        return evt;
    }

    public static void report() {
        Datetime endx = System.now();
        evt.End__c = endx;
        evt.EndTimeMillis__c = endx.getTime();
        evt.RuntimeMillis__c = evt.EndTimeMillis__c - evt.StartTimeMillis__c;
        Eventbus.publish(evt);
    }

    public static void normalize(Id jobId) {
        List<BatchChunkLog__c> logs = [
            SELECT Id, Start__c
            FROM BatchChunkLog__c
            WHERE JobId__c = :jobId
            ORDER BY StartTimeMillis__c
        ];
        if (logs.size() > 1) {
            for (Integer i= 1; i < logs.size(); i++) {
                logs[i].PreviousChunkLog__c = logs[i-1].Id;
            }
            update logs;
        }
    }
}